<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="exalogic-10" ignored="0" name="Default test" tests="9" failures="1" timestamp="08 Jan 2018 04:57:39 GMT" time="8.797" errors="0">
  <testcase name="magicWandVerify_TC_001" time="0.71" classname="com.inmegh_school.test.regression.VerifyDashboardPage_SC_002"/>
  <testcase name="adminDropdownVerify_TC_002" time="0.309" classname="com.inmegh_school.test.regression.VerifyDashboardPage_SC_002"/>
  <testcase name="notificationVerify_TC_003" time="0.299" classname="com.inmegh_school.test.regression.VerifyDashboardPage_SC_002"/>
  <testcase name="rightToggleVerify_TC_004" time="0.102" classname="com.inmegh_school.test.regression.VerifyDashboardPage_SC_002"/>
  <testcase name="settingVerify_TC_005" time="0.433" classname="com.inmegh_school.test.regression.VerifyDashboardPage_SC_002"/>
  <testcase name="attendanceStatusVerify_TC_006" time="0.323" classname="com.inmegh_school.test.regression.VerifyDashboardPage_SC_002"/>
  <testcase name="financeStatusVerify_TC_007" time="0.297" classname="com.inmegh_school.test.regression.VerifyDashboardPage_SC_002"/>
  <testcase name="sideToggleVerify_TC_008" time="0.349" classname="com.inmegh_school.test.regression.VerifyDashboardPage_SC_002"/>
  <testcase name="signOutVerify_TC_009" time="0.007" classname="com.inmegh_school.test.regression.VerifyDashboardPage_SC_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.inmegh_school.test.regression.VerifyDashboardPage_SC_002.signOutVerify_TC_009(VerifyDashboardPage_SC_002.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- signOutVerify_TC_009 -->
</testsuite> <!-- Default test -->
